// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig, env } from "prisma/config";

// .env.local 우선 로드 (Next.js 규칙)
config({ path: ".env.local" });
config({ path: ".env" }); // fallback

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // db pull/introspection은 direct connection이 필요
    // Supabase pooler (6543)는 PgBouncer이므로 direct URL (5432) 사용
    url: env("DIRECT_URL"),
    directUrl: process.env.DIRECT_URL,
  },
});
